language: node_js
node_js: 11
scripts:
- yarn
jobs:
  include:
  - stage: build
    name: Build Lib
    script:
        - npm run lint
        - npm run test
        - npm run build
  - stage: deploy
    name: Deploy Lib
    before_deploy:
    - yarn build
    deploy:
      provider: npm
      email: stesel23@gmail.com
      api_key: $NPM_AUTH_TOKEN
      skip_cleanup: true
      tag: alpha
      on:
        branch: master
